//! Shell integration scripts

/// Bash integration script
pub const BASH_INTEGRATION: &str = r#"
# Navr Shell Integration
# Generated by navr shell install bash

# Enable completion
if command -v navr &> /dev/null; then
    eval "$(navr shell complete bash)"
fi

# Navr cd wrapper function
qn_cd() {
    local target="$1"
    
    if [[ -z "$target" ]]; then
        builtin cd ~
    elif [[ -d "$target" ]]; then
        builtin cd "$target"
    else
        # Try to resolve via navr
        local resolved
        resolved=$(navr jump "$target" 2>/dev/null)
        if [[ -n "$resolved" ]]; then
            # Check if output has NAVR_JUMP prefix
            if [[ "$resolved" =~ ^NAVR_JUMP:(.+)$ ]]; then
                builtin cd "${BASH_REMATCH[1]}"
            else
                builtin cd "$resolved"
            fi
        else
            builtin cd "$target"
        fi
    fi
}

# Override cd command
cd() {
    qn_cd "$@"
}

# Navr aliases
alias j='navr jump'
alias jo='navr open'
alias jl='navr jump --list'
alias jc='navr config show'

# Function to jump and list
jcd() {
    cd "$@" && ls
}

# Tab completion for navr
_navr_jump_complete() {
    local cur="${COMP_WORDS[COMP_CWORD]}"
    local shortcuts
    shortcuts=$(navr jump --list 2>/dev/null | awk '/^  [a-zA-Z]/ {print $1}')
    COMPREPLY=($(compgen -W "$shortcuts" -- "$cur"))
}

complete -F _navr_jump_complete navr jump
complete -F _navr_jump_complete j
"#;

/// Zsh integration script
pub const ZSH_INTEGRATION: &str = r#"
# Navr Shell Integration
# Generated by navr shell install zsh

# Enable completion
if (( $+commands[navr] )); then
    eval "$(navr shell complete zsh)"
fi

# Navr cd wrapper function
qn_cd() {
    local target="$1"
    
    if [[ -z "$target" ]]; then
        builtin cd ~
    elif [[ -d "$target" ]]; then
        builtin cd "$target"
    else
        # Try to resolve via navr
        local resolved
        resolved=$(navr jump "$target" 2>/dev/null)
        if [[ -n "$resolved" ]]; then
            # Check if output has NAVR_JUMP prefix
            if [[ "$resolved" =~ ^NAVR_JUMP:(.+)$ ]]; then
                builtin cd "${match[1]}"
            else
                builtin cd "$resolved"
            fi
        else
            builtin cd "$target"
        fi
    fi
}

# Override cd command
cd() {
    qn_cd "$@"
}

# Navr aliases
alias j='navr jump'
alias jo='navr open'
alias jl='navr jump --list'
alias jc='navr config show'

# Function to jump and list
jcd() {
    cd "$@" && ls
}

# Zsh completion function
_navr_complete() {
    local -a shortcuts
    local lines
    lines=(${(f)"$(navr jump --list 2>/dev/null | awk '/^  [a-zA-Z]/ {print $1}')"})
    shortcuts=($lines)
    _describe -t shortcuts 'shortcut' shortcuts
}

compdef _navr_complete navr jump
compdef _navr_complete j
"#;

/// Fish integration script
pub const FISH_INTEGRATION: &str = r#"
# Navr Shell Integration
# Generated by navr shell install fish

# Enable completion
if command -sq navr
    navr shell complete fish | source
end

# Navr cd wrapper function
function qn_cd
    set -l target $argv[1]
    
    if test -z "$target"
        builtin cd ~
    else if test -d "$target"
        builtin cd "$target"
    else
        # Try to resolve via navr
        set -l resolved (navr jump "$target" 2>/dev/null)
        if test -n "$resolved"
            # Check if output has NAVR_JUMP prefix
            if string match -q 'NAVR_JUMP:*' "$resolved"
                set -l jump_path (string replace -r '^NAVR_JUMP:(.+)$' '$1' "$resolved")
                builtin cd "$jump_path"
            else
                builtin cd "$resolved"
            end
        else
            builtin cd "$target"
        end
    end
end

# Override cd command (in fish, we use a wrapper)
functions -c cd builtin_cd 2>/dev/null
function cd
    qn_cd $argv
end

# Navr aliases
alias j 'navr jump'
alias jo 'navr open'
alias jl 'navr jump --list'
alias jc 'navr config show'

# Function to jump and list
function jcd
    cd $argv && ls
end

# Fish completions
complete -c navr -f
complete -c navr -n '__fish_use_subcommand' -a 'jump' -d 'Jump to directory'
complete -c navr -n '__fish_use_subcommand' -a 'open' -d 'Open in file manager'
complete -c navr -n '__fish_use_subcommand' -a 'config' -d 'Manage configuration'
complete -c navr -n '__fish_use_subcommand' -a 'shell' -d 'Shell integration'
complete -c navr -n '__fish_use_subcommand' -a 'export' -d 'Export configuration'
complete -c navr -n '__fish_use_subcommand' -a 'import' -d 'Import configuration'

# Dynamic shortcut completion
complete -c navr -n '__fish_seen_subcommand_from jump' -a '(navr jump --list 2>/dev/null | string match -r "^  (\w+)" | string replace -r "^  " "")'
complete -c j -a '(navr jump --list 2>/dev/null | string match -r "^  (\w+)" | string replace -r "^  " "")'
"#;

/// PowerShell integration script
pub const POWERSHELL_INTEGRATION: &str = r#"
# =============================================================================
#
# Utility functions for navr.
#

# Call navr binary, returning the output as UTF-8.
function global:__navr_bin {
    $encoding = [Console]::OutputEncoding
    try {
        [Console]::OutputEncoding = [System.Text.Utf8Encoding]::new()
        $result = navr @args
        return $result
    } finally {
        [Console]::OutputEncoding = $encoding
    }
}

# pwd based on navr's format.
function global:__navr_pwd {
    $cwd = Get-Location
    if ($cwd.Provider.Name -eq "FileSystem") {
        $cwd.ProviderPath
    }
}

# cd + custom logic based on navr integration.
function global:__navr_cd($dir, $literal) {
    if ($literal) {
        Set-Location -LiteralPath $dir -Passthru -ErrorAction Stop
    } else {
        if ($dir -eq '-' -and ($PSVersionTable.PSVersion -lt 6.1)) {
            Write-Error "cd - is not supported below PowerShell 6.1. Please upgrade your version of PowerShell."
        }
        elseif ($dir -eq '+' -and ($PSVersionTable.PSVersion -lt 6.2)) {
            Write-Error "cd + is not supported below PowerShell 6.2. Please upgrade your version of PowerShell."
        }
        else {
            Set-Location -Path $dir -Passthru -ErrorAction Stop
        }
    }
}

# =============================================================================
#
# Hook configuration for navr.
#

# Hook to add new entries to the database.
$global:__navr_oldpwd = __navr_pwd
function global:__navr_hook {
    $result = __navr_pwd
    if ($result -ne $global:__navr_oldpwd) {
        if ($null -ne $result) {
            navr add "--" $result
        }
        $global:__navr_oldpwd = $result
    }
}

# Initialize hook.
$global:__navr_hooked = (Get-Variable __navr_hooked -ErrorAction Ignore -ValueOnly)
if ($global:__navr_hooked -ne 1) {
    $global:__navr_hooked = 1
    $global:__navr_prompt_old = $function:prompt
    
    function global:prompt {
        if ($null -ne $__navr_prompt_old) {
            & $__navr_prompt_old
        }
        $null = __navr_hook
    }
}

# =============================================================================
#
# When using navr with --no-cmd, alias these internal functions as desired.
#

# Jump to a directory using only keywords.
function global:__navr_jump {
    if ($args.Length -eq 0) {
        __navr_cd ~ $true
    }
    elseif ($args.Length -eq 1 -and ($args[0] -eq '-' -or $args[0] -eq '+')) {
        __navr_cd $args[0] $false
    }
    elseif ($args.Length -eq 1 -and (Test-Path -PathType Container -LiteralPath $args[0])) {
        __navr_cd $args[0] $true
    }
    elseif ($args.Length -eq 1 -and (Test-Path -PathType Container -Path $args[0] )) {
        __navr_cd $args[0] $false
    }
    else {
        $result = __navr_pwd
        if ($null -ne $result) {
            $result = __navr_bin jump "--" @args
        }
        else {
            $result = __navr_bin jump "--" @args
        }
        if ($LASTEXITCODE -eq 0) {
            __navr_cd $result $true
        }
    }
}

# Open directory in file manager.
function global:__navr_open {
    __navr_bin open "--" @args
}

# List all shortcuts.
function global:__navr_list {
    __navr_bin jump --list "--" @args
}

# Show configuration.
function global:__navr_config {
    __navr_bin config show "--" @args
}

# =============================================================================
#
# Commands for navr. Disable these using --no-cmd.
#

Set-Alias -Name j -Value __navr_jump -Option AllScope -Scope Global -Force
Set-Alias -Name jo -Value __navr_open -Option AllScope -Scope Global -Force
Set-Alias -Name jl -Value __navr_list -Option AllScope -Scope Global -Force
Set-Alias -Name jc -Value __navr_config -Option AllScope -Scope Global -Force

# Override Set-Location (cd) with navr integration
function global:Set-LocationNavr {
    param([string]$Path)
    
    if ([string]::IsNullOrEmpty($Path)) {
        __navr_cd ~ $true
    } elseif (Test-Path -Path $Path -PathType Container) {
        __navr_cd $Path $false
    } else {
        # Try to resolve via navr
        $result = __navr_bin jump "--" $Path
        if ($LASTEXITCODE -eq 0) {
            __navr_cd $result $true
        } else {
            __navr_cd $Path $false
        }
    }
}

Set-Alias -Name cd -Value Set-LocationNavr -Option AllScope -Scope Global -Force

# Tab completion
Register-ArgumentCompleter -CommandName navr -ParameterName target -ScriptBlock {
    param($commandName, $parameterName, $wordToComplete, $commandAst, $fakeBoundParameters)
    
    $shortcuts = & navr jump --list 2>$null | 
        Select-String -Pattern '^  (\w+)' | 
        ForEach-Object { $_.Matches.Groups[1].Value }
    
    $shortcuts | Where-Object { $_ -like "$wordToComplete*" } | 
        ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }
}

Register-ArgumentCompleter -CommandName j -ScriptBlock {
    param($commandName, $parameterName, $wordToComplete, $commandAst, $fakeBoundParameters)
    
    $shortcuts = & navr jump --list 2>$null | 
        Select-String -Pattern '^  (\w+)' | 
        ForEach-Object { $_.Matches.Groups[1].Value }
    
    $shortcuts | Where-Object { $_ -like "$wordToComplete*" } | 
        ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }
}

# =============================================================================
#
# To initialize navr, add this to your configuration (find it by running
# `echo $profile` in PowerShell):
#
# Invoke-Expression (& { (navr shell init powershell | Out-String) })
"#;

/// Elvish integration script
pub const ELVISH_INTEGRATION: &str = r#"
# Navr Shell Integration
# Generated by navr shell install elvish

# Enable completion
if (has-external navr) {
    eval (navr shell complete elvish | slurp)
}

# Navr cd wrapper function
fn qn_cd [target]{
    if (eq $target "") {
        cd ~
    } elif (path:is-dir $target) {
        cd $target
    } else {
        # Try to resolve via navr
        resolved = (navr jump $target 2>/dev/null)
        if (not (eq $resolved "")) {
            cd $resolved
        } else {
            cd $target
        }
    }
}

# Override cd command
fn cd [target]{
    qn_cd $target
}

# Quick navigation aliases
fn j [target]{
    qn_cd $target
}

fn jo [target]{
    navr open $target
}

fn jl {
    navr jump --list
}

fn jc {
    navr config show
}

# Function to jump and list
fn jcd [target]{
    qn_cd $target
    ls
}
"#;

// /// Generate a POSIX-compatible wrapper script
// pub fn generate_posix_wrapper() -> String {
//     r#"#!/bin/sh
// # Navr POSIX wrapper script
// # This script can be sourced to enable navr functionality in any POSIX shell

// # Main wrapper function
// navr_cd() {
//     _qn_target="$1"
    
//     if [ -z "$_qn_target" ]; then
//         cd ~
//     elif [ -d "$_qn_target" ]; then
//         cd "$_qn_target"
//     else
//         # Try to resolve via navr
//         _qn_resolved=$(navr jump "$_qn_target" 2>/dev/null)
//         if [ -n "$_qn_resolved" ] && [ -d "$_qn_resolved" ]; then
//             cd "$_qn_resolved"
//         else
//             cd "$_qn_target"
//         fi
//     fi
    
//     unset _qn_target _qn_resolved
// }

// # Set up aliases
// alias j='navr jump'
// alias jo='navr open'
// alias jl='navr jump --list'
// "#.to_string()
// }
