//! Shell integration scripts

/// Bash integration script
pub const BASH_INTEGRATION: &str = r#"
# Navr Shell Integration
# Generated by navr shell install bash

# Enable completion
if command -v navr &> /dev/null; then
    eval "$(navr shell complete bash)"
fi

# Navr cd wrapper function
qn_cd() {
    local target="$1"
    
    if [[ -z "$target" ]]; then
        builtin cd ~
    elif [[ -d "$target" ]]; then
        builtin cd "$target"
    else
        # Try to resolve via navr
        local resolved
        resolved=$(navr jump "$target" 2>/dev/null)
        if [[ -n "$resolved" ]]; then
            # Check if output has NAVR_JUMP prefix
            if [[ "$resolved" =~ ^NAVR_JUMP:(.+)$ ]]; then
                builtin cd "${BASH_REMATCH[1]}"
            else
                builtin cd "$resolved"
            fi
        else
            builtin cd "$target"
        fi
    fi
}

# Override cd command
cd() {
    qn_cd "$@"
}

# Navr aliases
alias j='navr jump'
alias jo='navr open'
alias jl='navr jump --list'
alias jc='navr config show'

# Function to jump and list
jcd() {
    cd "$@" && ls
}

# Tab completion for navr
_navr_jump_complete() {
    local cur="${COMP_WORDS[COMP_CWORD]}"
    local shortcuts
    shortcuts=$(navr jump --list 2>/dev/null | awk '/^  [a-zA-Z]/ {print $1}')
    COMPREPLY=($(compgen -W "$shortcuts" -- "$cur"))
}

complete -F _navr_jump_complete navr jump
complete -F _navr_jump_complete j
"#;

/// Zsh integration script
pub const ZSH_INTEGRATION: &str = r#"
# Navr Shell Integration
# Generated by navr shell install zsh

# Enable completion
if (( $+commands[navr] )); then
    eval "$(navr shell complete zsh)"
fi

# Navr cd wrapper function
qn_cd() {
    local target="$1"
    
    if [[ -z "$target" ]]; then
        builtin cd ~
    elif [[ -d "$target" ]]; then
        builtin cd "$target"
    else
        # Try to resolve via navr
        local resolved
        resolved=$(navr jump "$target" 2>/dev/null)
        if [[ -n "$resolved" ]]; then
            # Check if output has NAVR_JUMP prefix
            if [[ "$resolved" =~ ^NAVR_JUMP:(.+)$ ]]; then
                builtin cd "${match[1]}"
            else
                builtin cd "$resolved"
            fi
        else
            builtin cd "$target"
        fi
    fi
}

# Override cd command
cd() {
    qn_cd "$@"
}

# Navr aliases
alias j='navr jump'
alias jo='navr open'
alias jl='navr jump --list'
alias jc='navr config show'

# Function to jump and list
jcd() {
    cd "$@" && ls
}

# Zsh completion function
_navr_complete() {
    local -a shortcuts
    local lines
    lines=(${(f)"$(navr jump --list 2>/dev/null | awk '/^  [a-zA-Z]/ {print $1}')"})
    shortcuts=($lines)
    _describe -t shortcuts 'shortcut' shortcuts
}

compdef _navr_complete navr jump
compdef _navr_complete j
"#;

/// Fish integration script
pub const FISH_INTEGRATION: &str = r#"
# Navr Shell Integration
# Generated by navr shell install fish

# Enable completion
if command -sq navr
    navr shell complete fish | source
end

# Navr cd wrapper function
function qn_cd
    set -l target $argv[1]
    
    if test -z "$target"
        builtin cd ~
    else if test -d "$target"
        builtin cd "$target"
    else
        # Try to resolve via navr
        set -l resolved (navr jump "$target" 2>/dev/null)
        if test -n "$resolved"
            # Check if output has NAVR_JUMP prefix
            if string match -q 'NAVR_JUMP:*' "$resolved"
                set -l jump_path (string replace -r '^NAVR_JUMP:(.+)$' '$1' "$resolved")
                builtin cd "$jump_path"
            else
                builtin cd "$resolved"
            end
        else
            builtin cd "$target"
        end
    end
end

# Override cd command (in fish, we use a wrapper)
functions -c cd builtin_cd 2>/dev/null
function cd
    qn_cd $argv
end

# Navr aliases
alias j 'navr jump'
alias jo 'navr open'
alias jl 'navr jump --list'
alias jc 'navr config show'

# Function to jump and list
function jcd
    cd $argv && ls
end

# Fish completions
complete -c navr -f
complete -c navr -n '__fish_use_subcommand' -a 'jump' -d 'Jump to directory'
complete -c navr -n '__fish_use_subcommand' -a 'open' -d 'Open in file manager'
complete -c navr -n '__fish_use_subcommand' -a 'config' -d 'Manage configuration'
complete -c navr -n '__fish_use_subcommand' -a 'shell' -d 'Shell integration'
complete -c navr -n '__fish_use_subcommand' -a 'export' -d 'Export configuration'
complete -c navr -n '__fish_use_subcommand' -a 'import' -d 'Import configuration'

# Dynamic shortcut completion
complete -c navr -n '__fish_seen_subcommand_from jump' -a '(navr jump --list 2>/dev/null | string match -r "^  (\w+)" | string replace -r "^  " "")'
complete -c j -a '(navr jump --list 2>/dev/null | string match -r "^  (\w+)" | string replace -r "^  " "")'
"#;

/// PowerShell integration script
pub const POWERSHELL_INTEGRATION: &str = r#"
# Navr Shell Integration
# Generated by navr shell install powershell

# Enable completion
if (Get-Command navr -ErrorAction SilentlyContinue) {
    navr shell complete powershell | Out-String | Invoke-Expression
}

# Navr cd wrapper function
function Set-LocationNavr {
    param([string]$Path)
    
    if ([string]::IsNullOrEmpty($Path)) {
        Set-Location ~
    } elseif (Test-Path -Path $Path -PathType Container) {
        Set-Location $Path
    } else {
        # Try to resolve via navr
        $resolved = & navr jump $Path 2>$null
        if ($resolved) {
            # Check if output has NAVR_JUMP prefix
            if ($resolved -match '^NAVR_JUMP:(.+)$') {
                Set-Location $matches[1].Trim()
            } else {
                Set-Location $resolved
            }
        } else {
            Set-Location $Path
        }
    }
}

# Override Set-Location (cd)
Set-Alias -Name cd -Value Set-LocationNavr -Option AllScope -Force

# Navr navigation functions
function j {
    param([string]$target)
    $result = & navr jump $target 2>$null
    if ($result) {
        # Check if output has NAVR_JUMP prefix
        if ($result -match '^NAVR_JUMP:(.+)$') {
            Set-Location $matches[1].Trim()
        } else {
            Set-Location $result
        }
    }
}

function jo {
    param([string]$target)
    & navr open $target
}

function jl {
    & navr jump --list
}

function jc {
    & navr config show
}

# Function to jump and list
function jcd {
    param([string]$Path)
    Set-LocationNavr -Path $Path
    Get-ChildItem
}

# Tab completion
Register-ArgumentCompleter -CommandName navr -ParameterName target -ScriptBlock {
    param($commandName, $parameterName, $wordToComplete, $commandAst, $fakeBoundParameters)
    
    $shortcuts = & navr jump --list 2>$null | 
        Select-String -Pattern '^  (\w+)' | 
        ForEach-Object { $_.Matches.Groups[1].Value }
    
    $shortcuts | Where-Object { $_ -like "$wordToComplete*" } | 
        ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }
}

Register-ArgumentCompleter -CommandName j -ScriptBlock {
    param($commandName, $parameterName, $wordToComplete, $commandAst, $fakeBoundParameters)
    
    $shortcuts = & navr jump --list 2>$null | 
        Select-String -Pattern '^  (\w+)' | 
        ForEach-Object { $_.Matches.Groups[1].Value }
    
    $shortcuts | Where-Object { $_ -like "$wordToComplete*" } | 
        ForEach-Object { [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }
}
"#;

/// Elvish integration script
pub const ELVISH_INTEGRATION: &str = r#"
# Navr Shell Integration
# Generated by navr shell install elvish

# Enable completion
if (has-external navr) {
    eval (navr shell complete elvish | slurp)
}

# Navr cd wrapper function
fn qn_cd [target]{
    if (eq $target "") {
        cd ~
    } elif (path:is-dir $target) {
        cd $target
    } else {
        # Try to resolve via navr
        resolved = (navr jump $target 2>/dev/null)
        if (not (eq $resolved "")) {
            # Check if output has NAVR_JUMP prefix
            if (re:match '^NAVR_JUMP:(.+)$' $resolved) {
                jump_path = (re:replace '^NAVR_JUMP:(.+)$' '$1' $resolved)
                cd $jump_path
            } else {
                cd $resolved
            }
        } else {
            cd $target
        }
    }
}

# Override cd command
fn cd [target]{
    qn_cd $target
}

# Quick navigation aliases
fn j [target]{
    qn_cd $target
}

fn jo [target]{
    navr open $target
}

fn jl {
    navr jump --list
}

fn jc {
    navr config show
}

# Function to jump and list
fn jcd [target]{
    qn_cd $target
    ls
}
"#;

// /// Generate a POSIX-compatible wrapper script
// pub fn generate_posix_wrapper() -> String {
//     r#"#!/bin/sh
// # Navr POSIX wrapper script
// # This script can be sourced to enable navr functionality in any POSIX shell

// # Main wrapper function
// navr_cd() {
//     _qn_target="$1"
    
//     if [ -z "$_qn_target" ]; then
//         cd ~
//     elif [ -d "$_qn_target" ]; then
//         cd "$_qn_target"
//     else
//         # Try to resolve via navr
//         _qn_resolved=$(navr jump "$_qn_target" 2>/dev/null)
//         if [ -n "$_qn_resolved" ] && [ -d "$_qn_resolved" ]; then
//             cd "$_qn_resolved"
//         else
//             cd "$_qn_target"
//         fi
//     fi
    
//     unset _qn_target _qn_resolved
// }

// # Set up aliases
// alias j='navr jump'
// alias jo='navr open'
// alias jl='navr jump --list'
// "#.to_string()
// }
